[features]
seeds = false
[programs.localnet]
pathogen = "CYmfp3tVDFtfkK5TeTYbNKRT4kQa5it57jjgERaTpZwh"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/jasonwu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
