on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  setup-anchor-cli:
    name: Setup Anchor cli
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup/
      - run: |
          rustup install stable
          cargo --version
          docker --version
      - uses: actions/cache@v2
        name: Cache Cargo registry + index
        id: cache-anchor
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./target/
          key: cargo-${{ runner.os }}-anchor-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo install anchor-cli --locked
      - run: chmod +x ~/.cargo/bin/anchor
      - uses: actions/upload-artifact@v2
        with:
          name: anchor-binary
          path: ~/.cargo/bin/anchor

  build-and-test:
    needs: setup-anchor-cli
    runs-on: ubuntu-20.04
    steps:
      - name: multiple paths
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: "${{ runner.os }}-${{ hashFiles('TODO') }}"
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: anchor-binary
          path: ~/.cargo/bin/
      - run: chmod +rwx ~/.cargo/bin/anchor
      - run: >-
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      - run: >-
          sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main"
      - run: |
          sudo apt-get update
          sudo apt-get install -y openssl --allow-unauthenticated
          sudo apt-get install -y libssl-dev --allow-unauthenticated
          sudo apt-get install -y clang-7 --allow-unauthenticated
          sudo apt-get install -y libssl1.1 --allow-unauthenticated
          clang-7 --version
          node --version
      - run: |
          sh -c "$(curl -sSfL https://release.solana.com/v1.8.14/install)"
          export PATH=~/.local/share/solana/install/active_release/bin:$PATH
          solana-install info
          solana-keygen new --no-bip39-passphrase
      - run: |
          yarn
      - run: |
          anchor test
